CREATE TABLE IF NOT EXISTS files (
    fileId INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(255) NOT NULL,    extension VARCHAR(10),    size INT NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);